services:
  transactions-db:
    build:
      context: ./docker/postgres-db
    environment:
      - POSTGRES_USER=finance_db_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=finance_db
    volumes:
        - "${PWD}/db-data:/var/lib/postgresql/data"
        - "${PWD}/db-scripts/initialize_db_ddl.sql:/docker-entrypoint-initdb.d/initialize_db_ddl.sql"
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "wal_level=logical", "-c", "hot_standby=on"]

  api:
      build:
        context: ./api
      ports:
        - "8000:8000"
      environment:
        - SQLALCHEMY_DATABASE_URL=postgresql://finance_db_user:1234@transactions-db:5432/finance_db
      depends_on:
        - transactions-db